(()=>{
let pc=null,signalChannel=null,signalMatchId=null,seen=new Set(),pendingIce=[],offerBusy=false,remoteLive=false;
const rtcConfig={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]};
const el=id=>document.getElementById(id);
function opponentId(){if(!currentMatch||!user)return null;return user.id===currentMatch.host_id?currentMatch.guest_id:currentMatch.host_id}
function isHost(){return !!currentMatch&&user?.id===currentMatch.host_id}
function setConn(text,state=''){const n=el('connectionState');if(!n)return;n.textContent=text;n.className='connectionState '+state}
function setRemoteLive(on){remoteLive=on;const f=el('opponentFrame');if(f)f.classList.toggle('remote-live',!!on);if(!on){const v=el('opponentVideo');if(v)v.srcObject=null}}
async function sendSignal(type,payload){if(!currentMatch||!user)return;const{error}=await db.from('battle_signals').insert({match_id:currentMatch.id,sender_id:user.id,signal_type:type,payload});if(error)console.error('BATTLE signal',error)}
async function flushIce(){if(!pc?.remoteDescription)return;for(const c of pendingIce.splice(0)){try{await pc.addIceCandidate(c)}catch(e){console.warn('ICE',e)}}}
function makePeer(){if(pc)return pc;pc=new RTCPeerConnection(rtcConfig);if(stream)stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>{if(e.candidate)sendSignal('ice',{candidate:e.candidate.toJSON()})};pc.ontrack=e=>{const v=el('opponentVideo');if(!v)return;v.srcObject=e.streams[0]||new MediaStream([e.track]);setRemoteLive(true);setConn('LIVE VERBUNDEN','live')};pc.onconnectionstatechange=()=>{const s=pc?.connectionState;if(s==='connected'){setConn('LIVE VERBUNDEN','live');setRemoteLive(true)}else if(s==='connecting'||s==='new'){setConn('VERBINDUNG WIRD AUFGEBAUT','connecting')}else if(s==='disconnected'){setConn('VERBINDUNG UNTERBROCHEN','failed');setRemoteLive(false)}else if(s==='failed'){setConn('P2P VERBINDUNG FEHLGESCHLAGEN','failed');setRemoteLive(false)}else if(s==='closed'){setConn('KAMERA GETRENNT','');setRemoteLive(false)}};return pc}
async function handleSignal(row){if(!row||seen.has(row.id)||row.sender_id===user?.id)return;seen.add(row.id);if(!currentMatch||row.match_id!==currentMatch.id)return;try{if(row.signal_type==='offer'){const p=makePeer();await p.setRemoteDescription(new RTCSessionDescription(row.payload.sdp));await flushIce();const ans=await p.createAnswer();await p.setLocalDescription(ans);await sendSignal('answer',{sdp:{type:p.localDescription.type,sdp:p.localDescription.sdp}});setConn('VERBINDUNG WIRD AUFGEBAUT','connecting')}else if(row.signal_type==='answer'){if(!pc)return;await pc.setRemoteDescription(new RTCSessionDescription(row.payload.sdp));await flushIce()}else if(row.signal_type==='ice'){const c=row.payload?.candidate;if(!c)return;if(pc?.remoteDescription)await pc.addIceCandidate(new RTCIceCandidate(c));else pendingIce.push(new RTCIceCandidate(c))}else if(row.signal_type==='hangup'){shutdownPeer(false);setConn('GEGNERKAMERA GETRENNT','')}}catch(e){console.error('BATTLE WebRTC',e);setConn('VERBINDUNGSFEHLER','failed')}}
async function subscribeSignals(){if(!currentMatch||signalMatchId===currentMatch.id)return;if(signalChannel)await db.removeChannel(signalChannel);signalMatchId=currentMatch.id;seen.clear();pendingIce=[];await db.rpc('clear_my_battle_signals',{p_match_id:currentMatch.id});signalChannel=db.channel('battle-signal-'+currentMatch.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'battle_signals',filter:`match_id=eq.${currentMatch.id}`},p=>handleSignal(p.new)).subscribe(async status=>{if(status==='SUBSCRIBED'){const{data}=await db.from('battle_signals').select('*').eq('match_id',currentMatch.id).order('id',{ascending:true}).limit(80);for(const r of data||[])await handleSignal(r);maybeOffer()}})}
async function maybeOffer(){if(!currentMatch||!stream||!opponentId()||!isHost()||offerBusy)return;await subscribeSignals();if(pc?.localDescription?.type==='offer'||pc?.remoteDescription)return;offerBusy=true;try{const p=makePeer();const offer=await p.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:true});await p.setLocalDescription(offer);await sendSignal('offer',{sdp:{type:p.localDescription.type,sdp:p.localDescription.sdp}});setConn('WARTE AUF GEGENKAMERA','connecting')}catch(e){console.error(e);setConn('VERBINDUNG KONNTE NICHT STARTEN','failed')}finally{offerBusy=false}}
function shutdownPeer(send=true){if(send&&currentMatch)sendSignal('hangup',{});if(pc){pc.ontrack=null;pc.onicecandidate=null;pc.onconnectionstatechange=null;pc.close();pc=null}pendingIce=[];offerBusy=false;setRemoteLive(false)}
async function startMedia(){if(stream)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true}});el('myVideo').srcObject=stream;el('myVideoFallback').classList.add('hidden');el('cameraBtn').textContent='KAMERA STOPPEN';el('micBtn')?.classList.remove('hidden');setConn(opponentId()?'VERBINDUNG WIRD AUFGEBAUT':'KAMERA BEREIT · WARTE AUF GEGNER','connecting');await subscribeSignals();if(isHost())await maybeOffer()}catch(e){console.error(e);alert('Kamera oder Mikrofon konnte nicht geöffnet werden. Bitte Browser-Berechtigungen prüfen.')}}
async function stopMedia(){shutdownPeer(true);if(currentMatch&&['waiting','ready'].includes(currentMatch.status)){await db.rpc('set_battle_ready',{p_match_id:currentMatch.id,p_ready:false});refreshMatch()}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}el('myVideo').srcObject=null;el('myVideoFallback').classList.remove('hidden');el('cameraBtn').textContent=L().camera;el('micBtn')?.classList.add('hidden');setConn('KAMERA NICHT AKTIV','')}
async function toggleCamera(){if(stream)return stopMedia();return startMedia()}
function toggleMic(){if(!stream)return;const tracks=stream.getAudioTracks();if(!tracks.length)return;const enabled=!tracks[0].enabled;tracks.forEach(t=>t.enabled=enabled);el('micBtn').textContent=enabled?'MIKRO STUMM':'MIKRO AN'}
function sync(){if(!currentMatch)return;const oid=opponentId();const rb=el('reportUser');if(rb)rb.classList.toggle('hidden',!oid);if(stream){subscribeSignals();if(isHost()&&oid)maybeOffer()}if(!oid&&!remoteLive)setConn(stream?'KAMERA BEREIT · WARTE AUF GEGNER':'KAMERA NICHT AKTIV',stream?'connecting':'')}
async function sendReport(){if(!currentMatch||!opponentId())return;const cat=el('reportCategory').value,details=el('reportDetails').value.trim();el('reportMsg').textContent='Meldung wird gesendet …';const{error}=await db.rpc('report_battle_user',{p_match_id:currentMatch.id,p_reported_user_id:opponentId(),p_category:cat,p_details:details||null});if(error){el('reportMsg').textContent='Meldung konnte nicht gesendet werden.';return}el('reportMsg').textContent='Meldung wurde vertraulich gespeichert.';el('reportDetails').value='';setTimeout(()=>el('reportDialog').close(),900)}
const oldReady=el('readyBtn').onclick;el('readyBtn').onclick=async e=>{if(!stream||!stream.getVideoTracks().some(t=>t.readyState==='live')){alert('Aktiviere zuerst deine Kamera. BATTLE V1 ist ein Webcam-Match.');return}return oldReady?.call(el('readyBtn'),e)};
const oldLeave=el('leaveMatch').onclick;el('leaveMatch').onclick=async e=>{shutdownPeer(true);if(signalChannel){await db.removeChannel(signalChannel);signalChannel=null;signalMatchId=null}return oldLeave?.call(el('leaveMatch'),e)};
const oldLogout=el('logout').onclick;el('logout').onclick=async e=>{shutdownPeer(true);if(signalChannel){await db.removeChannel(signalChannel);signalChannel=null}return oldLogout?.call(el('logout'),e)};
el('cameraBtn').onclick=toggleCamera;if(el('micBtn'))el('micBtn').onclick=toggleMic;if(el('reportUser'))el('reportUser').onclick=()=>{el('reportMsg').textContent='';el('reportDialog').showModal()};if(el('sendReport'))el('sendReport').onclick=sendReport;
setInterval(sync,1200);
window.addEventListener('beforeunload',()=>{shutdownPeer(false);if(signalChannel)db.removeChannel(signalChannel)});
window.DV_BATTLE_RTC={startMedia,stopMedia,sync,shutdownPeer};
})();