(() => {
  'use strict';
  const db=window.supabase.createClient(window.DV_SUPABASE.url,window.DV_SUPABASE.key);
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const params=new URLSearchParams(location.search),listingFromUrl=params.get('listing')||'';
  $('listingId').value=listingFromUrl;if(listingFromUrl)$('listingSummary').innerHTML=`Gemeldetes Angebot: <b>${esc(listingFromUrl)}</b>`;
  function setMode(mode){const status=mode==='status';$('noticeForm').classList.toggle('hidden',status);$('receipt').classList.add('hidden');$('statusForm').classList.toggle('hidden',!status);$('statusResult').classList.add('hidden');$('newTab').classList.toggle('active',!status);$('statusTab').classList.toggle('active',status)}
  $('newTab').onclick=()=>setMode('new');$('statusTab').onclick=()=>setMode('status');
  $('noticeForm').addEventListener('submit',async event=>{
    event.preventDefault();const button=$('submitNotice'),message=$('noticeMessage');message.className='message';message.textContent='';if(!event.currentTarget.reportValidity())return;button.disabled=true;
    try{const listingId=$('listingId').value.trim(),exactUrl=`${location.origin}/trade.html?listing=${encodeURIComponent(listingId)}`;const {data,error}=await db.rpc('submit_marketplace_listing_notice',{p_listing_id:listingId,p_category:$('category').value,p_explanation:$('explanation').value.trim(),p_alleged_legal_basis:$('legalBasis').value.trim()||null,p_reporter_name:$('reporterName').value.trim(),p_reporter_email:$('reporterEmail').value.trim(),p_exact_url:exactUrl,p_good_faith_confirmed:$('goodFaith').checked});if(error)throw error;$('noticeForm').classList.add('hidden');$('receipt').classList.remove('hidden');$('receipt').innerHTML=`<h2>Meldung eingegangen</h2><p>Bitte bewahre beide Angaben auf. Der Zugangscode wird nur hier vollständig angezeigt.</p><b>Vorgangsnummer</b><span class="code">${esc(data.case_reference)}</span><b>Zugangscode</b><span class="code">${esc(data.access_code)}</span><p>Der Eingang wurde protokolliert. Nach der Prüfung erhältst du eine begründete Entscheidung und Informationen zu möglichen Rechtsbehelfen.</p>`;$('caseReference').value=data.case_reference;$('accessCode').value=data.access_code}
    catch(error){message.className='message error';message.textContent=humanError(error.message)}finally{button.disabled=false}
  });
  $('statusForm').addEventListener('submit',async event=>{event.preventDefault();if(!event.currentTarget.reportValidity())return;const message=$('statusMessage');message.className='message';message.textContent='';try{const {data,error}=await db.rpc('get_marketplace_notice_status',{p_case_reference:$('caseReference').value.trim(),p_access_code:$('accessCode').value.trim()});if(error)throw error;renderStatus(data)}catch(error){message.className='message error';message.textContent=humanError(error.message)}});
  function renderStatus(data){const labels={submitted:'Eingegangen',under_review:'In Prüfung',decided_no_action:'Entschieden · keine Maßnahme',decided_restricted:'Entschieden · Sichtbarkeit eingeschränkt',decided_removed:'Entschieden · entfernt',appealed:'Einspruch in Prüfung',closed:'Abgeschlossen'},decision=data.decision;$('statusResult').classList.remove('hidden');$('statusResult').innerHTML=`<h2>${esc(data.case_reference)}</h2><p>Status: <b>${esc(labels[data.status]||data.status)}</b></p><p>Angebot: ${esc(data.listing?.title||data.listing?.id||'nicht mehr verfügbar')}</p>${decision?`<div class="decision"><b>Begründete Entscheidung</b><p>${esc(decision.reason)}</p>${decision.reference?`<p>Grundlage: ${esc(decision.reference)}</p>`:''}<p>Automatisierte Entscheidung: ${decision.automated_means_used?'Ja':'Nein'}</p><p>${esc(decision.redress)}</p></div>${appealMarkup(data)}`:'<p>Die Meldung wird zeitnah, sorgfältig, objektiv und nicht willkürlich geprüft.</p>'}`;$('submitAppeal')?.addEventListener('click',submitAppeal)}
  function appealMarkup(data){if((data.appeals||[]).some(item=>['submitted','under_review'].includes(item.status)))return '<div class="appealBox"><b>Einspruch eingegangen</b><p>Der Einspruch wird durch eine Person geprüft.</p></div>';return '<div class="appealBox"><b>Interner Einspruch</b><p>Begründe konkret, warum die Entscheidung überprüft werden soll.</p><textarea id="appealGrounds" minlength="30" maxlength="5000" rows="5"></textarea><button id="submitAppeal" class="primary" type="button">EINSPRUCH EINLEGEN</button><p id="appealMessage" class="message" aria-live="polite"></p></div>'}
  async function submitAppeal(){const grounds=$('appealGrounds').value.trim(),message=$('appealMessage');if(grounds.length<30){message.className='message error';message.textContent='Bitte begründe den Einspruch mit mindestens 30 Zeichen.';return}try{const {error}=await db.rpc('submit_marketplace_notice_appeal',{p_case_reference:$('caseReference').value.trim(),p_access_code:$('accessCode').value.trim(),p_grounds:grounds});if(error)throw error;message.className='message';message.textContent='Einspruch eingegangen.';$('statusForm').requestSubmit()}catch(error){message.className='message error';message.textContent=humanError(error.message)}}
  function humanError(message=''){if(/listing_not_found|invalid input syntax for type uuid/i.test(message))return 'Das Angebot wurde nicht gefunden. Bitte öffne die Meldung direkt am betreffenden Angebot.';if(/notice_access_denied/i.test(message))return 'Vorgangsnummer oder Zugangscode stimmen nicht.';if(/rate_limit/i.test(message))return 'Zu viele Meldungen in kurzer Zeit. Bitte versuche es später erneut.';if(/explanation_invalid|grounds_invalid/i.test(message))return 'Die Begründung muss mindestens 30 Zeichen enthalten.';return 'Die Anfrage konnte nicht verarbeitet werden. Bitte prüfe deine Angaben und versuche es erneut.'}
})();
