(()=>{'use strict';
const config=window.DV_SUPABASE,production=config?.environment==='production',productionHost=['duelvanta.de','duelvantav5vision.vercel.app','duelvantav5vision-bennyescaped-3783.vercel.app','duelvantav5vision-git-main-bennyescaped-3783.vercel.app'].includes(location.hostname),expectedProject=production?'enifiaqsnqtbzylnfrpi':'xhmjxrcskfhbovhitdej';
if(!config||!['preview','production','development'].includes(config.environment)||production!==productionHost||(production&&location.protocol!=='https:')||config.url!==`https://${expectedProject}.supabase.co`||typeof config.key!=='string'||config.key!==config.key.trim()||!/^sb_publishable_[A-Za-z0-9_-]+$/.test(config.key))throw new Error('DUELVANTA MFA database is not safely configured');
const db=window.supabase.createClient(config.url,config.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=id=>document.getElementById(id),params=new URLSearchParams(location.search),required=params.get('required')==='1',manageMode=params.get('manage')==='1';let next=(params.get('next')||'app.html').replace(/[^a-zA-Z0-9._-]/g,''),activeFactor=null,verifiedFactors=[];
const show=id=>['challenge','enroll','manage'].forEach(x=>$(x).classList.toggle('hidden',x!==id)),msg=t=>$('msg').textContent=t,finish=()=>location.replace(next||'app.html');
async function factors(){const {data,error}=await db.auth.mfa.listFactors();if(error)throw error;verifiedFactors=[...(data?.totp||[])].filter(f=>f.status==='verified');return verifiedFactors}
async function assurance(){const {data,error}=await db.auth.mfa.getAuthenticatorAssuranceLevel();if(error)throw error;return data}
async function challenge(factorId,code){const c=await db.auth.mfa.challenge({factorId});if(c.error)throw c.error;const v=await db.auth.mfa.verify({factorId,challengeId:c.data.id,code:String(code||'').trim()});if(v.error)throw v.error;return v.data}
function renderManage(){show('manage');$('title').textContent='2FA verwalten';$('intro').textContent='Für privilegierte DUELVANTA-Aktionen ist ein verifizierter zweiter Faktor erforderlich.';$('factorList').innerHTML='';verifiedFactors.forEach((f,i)=>{const row=document.createElement('div');row.className='factor';const text=document.createElement('div');text.textContent=f.friendly_name||`Authenticator ${i+1}`;const b=document.createElement('button');b.className='danger';b.textContent='FAKTOR ENTFERNEN';b.onclick=async()=>{if(!confirm('Diesen zweiten Faktor wirklich entfernen?'))return;b.disabled=true;try{const {error}=await db.auth.mfa.unenroll({factorId:f.id});if(error)throw error;await db.auth.refreshSession();await factors();if(!verifiedFactors.length){msg('Kein 2FA-Faktor mehr aktiv.');return beginEnroll()}renderManage()}catch(e){msg('Faktor konnte nicht entfernt werden: '+e.message)}finally{b.disabled=false}};row.append(text,b);$('factorList').append(row)})}
async function beginEnroll(){show('enroll');$('title').textContent='2FA aktivieren';$('intro').textContent='Richte einen Authenticator-Faktor für diesen Account ein.';msg('');const {data,error}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'DUELVANTA Authenticator'});if(error){msg('2FA konnte nicht vorbereitet werden: '+error.message);return}activeFactor=data.id;$('qr').src=data.totp.qr_code;$('secret').textContent=data.totp.secret||'';$('enrollCode').value=''}
async function boot(){const {data:{session}}=await db.auth.getSession();if(!session){location.replace('login.html?next='+encodeURIComponent('mfa.html?next='+next));return}try{const [aal]=await Promise.all([assurance(),factors()]);if(manageMode){if(verifiedFactors.length&&aal.currentLevel!=='aal2'){activeFactor=verifiedFactors[0].id;show('challenge');$('title').textContent='2FA bestätigen';$('intro').textContent='Bestätige zuerst deinen zweiten Faktor, um die Sicherheitseinstellungen zu verwalten.';return}if(!verifiedFactors.length)return beginEnroll();return renderManage()}if(aal.currentLevel==='aal2')return finish();if(verifiedFactors.length){activeFactor=verifiedFactors[0].id;show('challenge');$('title').textContent='2FA bestätigen';$('intro').textContent='Dieser Account verwendet Zwei-Faktor-Authentifizierung.';return}if(required)return beginEnroll();finish()}catch(e){msg('2FA-Status konnte nicht geprüft werden: '+e.message)}}
$('verifyChallenge').onclick=async()=>{const code=$('challengeCode').value.trim();if(code.length<6)return msg('Bitte den Authenticator-Code eingeben.');$('verifyChallenge').disabled=true;try{await challenge(activeFactor,code);await factors();if(manageMode)return renderManage();finish()}catch(e){msg('Code konnte nicht bestätigt werden: '+e.message)}finally{$('verifyChallenge').disabled=false}};
$('verifyEnroll').onclick=async()=>{const code=$('enrollCode').value.trim();if(!activeFactor||code.length<6)return msg('Bitte den Authenticator-Code eingeben.');$('verifyEnroll').disabled=true;try{await challenge(activeFactor,code);activeFactor=null;await factors();msg('2FA ist aktiviert.');if(manageMode)return renderManage();finish()}catch(e){msg('2FA konnte nicht aktiviert werden: '+e.message)}finally{$('verifyEnroll').disabled=false}};
$('cancelEnroll').onclick=async()=>{if(activeFactor){await db.auth.mfa.unenroll({factorId:activeFactor}).catch(()=>{});activeFactor=null}if(manageMode&&verifiedFactors.length)return renderManage();finish()};$('addFactor').onclick=beginEnroll;$('done').onclick=finish;boot();})();