import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {summary,emptyMessage}=createRequire(import.meta.url)('../collect-ux.js');
const card=(purchase_price,market_price,quantity=1)=>({purchase_price,market_price,quantity});
assert.equal(summary([]).market.text,'—');
assert.equal(summary([card(null,null)]).market.text,'Nicht bewertet');
assert.equal(summary([card(null,null)]).purchase.text,'Keine Preisangaben');
const mixed=summary([card(4,10,2),card(null,null,3)]);
assert.equal(mixed.market.total,20);assert.match(mixed.market.note,/unvollständig/);assert.equal(mixed.profit,null);assert.equal(mixed.tone,'');
assert.equal(summary([card(0,0,3)]).profit,0);assert.equal(summary([card(0,0,3)]).market.missing,0);
assert.equal(summary([card(4,10,3),card(1,2,2)]).profit,20);
assert.equal(summary([card(null,10,2)]).profit,null);
assert.equal(summary([card(10,null,2)]).profit,null);
assert.equal(summary([card('0','0',2)]).profit,0);
assert.match(emptyMessage('ready','',0,0),/deiner Collection/);
assert.match(emptyMessage('ready','__graded__',0,0),/Graded Collection/);
assert.match(emptyMessage('ready','own',0,0),/diesem Binder/);
assert.match(emptyMessage('ready','own',2,0),/Suche oder Filter/);
assert.equal(emptyMessage('ready','own',2,1),'');
assert.match(emptyMessage('loading','',0,0),/wird geladen/);
assert.match(emptyMessage('error','',0,0),/nicht vollständig geladen/);
console.log('PASS COLLECT F1/F2 display fixtures');
