-- Spectator Media V1 server admission/consent foundation. Isolated CI first; never Production.
begin;
create schema if not exists battle_spectator_media_private;
revoke all on schema battle_spectator_media_private from public,anon,authenticated;
create table battle_spectator_media_private.config(singleton boolean primary key default true check(singleton),media_enabled boolean not null default false,max_viewers_per_match integer not null default 50 check(max_viewers_per_match between 0 and 10000),consent_version text not null default 'spectator-media-v1-2026-09');
insert into battle_spectator_media_private.config(singleton) values(true) on conflict do nothing;
create table battle_spectator_media_private.consents(match_id uuid not null references public.battle_matches(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,consent_version text not null,granted boolean not null,updated_at timestamptz not null default clock_timestamp(),primary key(match_id,user_id));
create table battle_spectator_media_private.epochs(match_id uuid primary key references public.battle_matches(id) on delete cascade,epoch uuid not null default gen_random_uuid(),generation uuid,media_open boolean not null default false,updated_at timestamptz not null default clock_timestamp());
create table battle_spectator_media_private.revocations(id bigint generated always as identity primary key,match_id uuid not null references public.battle_matches(id) on delete cascade,epoch uuid not null,reason text not null,state text not null default 'pending' check(state in('pending','processing','done')),created_at timestamptz not null default clock_timestamp(),unique(match_id,epoch,reason));
alter table battle_spectator_media_private.config enable row level security;alter table battle_spectator_media_private.consents enable row level security;alter table battle_spectator_media_private.epochs enable row level security;alter table battle_spectator_media_private.revocations enable row level security;
revoke all on all tables in schema battle_spectator_media_private from public,anon,authenticated;
create function battle_spectator_media_private.close_epoch(p_match uuid,p_reason text) returns void language plpgsql security definer set search_path='' as $$declare v_old uuid;begin select epoch into v_old from battle_spectator_media_private.epochs where match_id=p_match for update;if found then insert into battle_spectator_media_private.revocations(match_id,epoch,reason) values(p_match,v_old,p_reason) on conflict do nothing;update battle_spectator_media_private.epochs set epoch=gen_random_uuid(),generation=null,media_open=false,updated_at=clock_timestamp() where match_id=p_match;end if;end$$;
create function battle_spectator_media_private.sync_epoch(p_match uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare m public.battle_matches%rowtype;c battle_spectator_media_private.config%rowtype;g uuid;o boolean;e battle_spectator_media_private.epochs%rowtype;begin select * into m from public.battle_matches where id=p_match for share;if not found then raise exception 'spectator_media_unavailable' using errcode='42501';end if;select * into c from battle_spectator_media_private.config where singleton;select generation into g from battle_spectator_private.links where match_id=p_match and enabled;o:=c.media_enabled and m.guest_id is not null and m.status in('waiting','ready','live') and m.moderation_state is distinct from 'paused' and m.paused_at is null and exists(select 1 from battle_spectator_media_private.consents x where x.match_id=p_match and x.user_id=m.host_id and x.granted and x.consent_version=c.consent_version) and exists(select 1 from battle_spectator_media_private.consents x where x.match_id=p_match and x.user_id=m.guest_id and x.granted and x.consent_version=c.consent_version) and (m.visibility='public' or g is not null);select * into e from battle_spectator_media_private.epochs where match_id=p_match for update;if not found then insert into battle_spectator_media_private.epochs(match_id,generation,media_open) values(p_match,g,o) returning * into e;elsif e.generation is distinct from g or(e.media_open and not o) then perform battle_spectator_media_private.close_epoch(p_match,case when e.generation is distinct from g then 'generation_changed' else 'media_closed' end);update battle_spectator_media_private.epochs set generation=g,media_open=o where match_id=p_match returning * into e;elsif e.media_open is distinct from o then update battle_spectator_media_private.epochs set media_open=o where match_id=p_match returning * into e;end if;return jsonb_build_object('media_open',e.media_open,'epoch',e.epoch,'max_viewers_per_match',c.max_viewers_per_match,'consent_version',c.consent_version);end$$;
create function public.set_battle_spectator_media_consent(p_match_id uuid,p_granted boolean) returns jsonb language plpgsql security definer set search_path='' as $$declare m public.battle_matches%rowtype;c battle_spectator_media_private.config%rowtype;begin perform battle_spectator_private.actor_session();if p_granted is null then raise exception 'spectator_media_invalid_consent';end if;select * into m from public.battle_matches where id=p_match_id for share;if not found or (auth.uid() is distinct from m.host_id and auth.uid() is distinct from m.guest_id) or m.status not in('waiting','ready','live') then raise exception 'spectator_media_player_only' using errcode='42501';end if;select * into c from battle_spectator_media_private.config where singleton;insert into battle_spectator_media_private.consents values(p_match_id,auth.uid(),c.consent_version,p_granted,clock_timestamp()) on conflict(match_id,user_id) do update set consent_version=excluded.consent_version,granted=excluded.granted,updated_at=excluded.updated_at;if not p_granted then perform battle_spectator_media_private.close_epoch(p_match_id,'player_withdrawal');end if;return battle_spectator_media_private.sync_epoch(p_match_id);end$$;
create function public.get_battle_spectator_media_status(p_match_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare m public.battle_matches%rowtype;c battle_spectator_media_private.config%rowtype;s jsonb;begin perform battle_spectator_private.actor_session();select * into m from public.battle_matches where id=p_match_id;if not found or(auth.uid() is distinct from m.host_id and auth.uid() is distinct from m.guest_id) then raise exception 'spectator_media_player_only' using errcode='42501';end if;select * into c from battle_spectator_media_private.config where singleton;s:=battle_spectator_media_private.sync_epoch(p_match_id);return s||jsonb_build_object('my_consent',coalesce((select x.granted and x.consent_version=c.consent_version from battle_spectator_media_private.consents x where x.match_id=p_match_id and x.user_id=auth.uid()),false));end$$;
create function public.reserve_battle_spectator_media_viewer(p_match_id uuid,p_tab_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare sid uuid;s jsonb;begin sid:=battle_spectator_private.actor_session();if not exists(select 1 from battle_spectator_private.presence p where p.match_id=p_match_id and p.user_id=auth.uid() and p.session_id=sid and p.tab_id=p_tab_id and p.expires_at>clock_timestamp()) or not battle_spectator_private.authorized(p_match_id,auth.uid()) then raise exception 'spectator_media_presence_required' using errcode='42501';end if;s:=battle_spectator_media_private.sync_epoch(p_match_id);if not coalesce((s->>'media_open')::boolean,false) then raise exception 'spectator_media_closed' using errcode='42501';end if;return jsonb_build_object('match_id',p_match_id,'epoch',s->>'epoch','admission_expires_at',clock_timestamp()+interval '30 seconds','max_viewers_per_match',(s->>'max_viewers_per_match')::integer);end$$;

create function public.get_battle_spectator_media_publisher_admission(p_match_id uuid) returns jsonb
language plpgsql security definer set search_path='' as $media$
declare m public.battle_matches%rowtype; s jsonb; role_name text;
begin
  perform battle_spectator_private.actor_session();
  select * into m from public.battle_matches where id=p_match_id;
  if not found or (auth.uid() is distinct from m.host_id and auth.uid() is distinct from m.guest_id) then
    raise exception 'spectator_media_player_only' using errcode='42501';
  end if;
  s:=battle_spectator_media_private.sync_epoch(p_match_id);
  if not coalesce((s->>'media_open')::boolean,false) then
    raise exception 'spectator_media_closed' using errcode='42501';
  end if;
  role_name:=case when auth.uid()=m.host_id then 'host' else 'guest' end;
  return jsonb_build_object('match_id',p_match_id,'epoch',s->>'epoch','publisher_role',role_name,'admission_expires_at',clock_timestamp()+interval '30 seconds');
end
$media$;
revoke all on all functions in schema battle_spectator_media_private from public,anon,authenticated;
revoke all on function public.set_battle_spectator_media_consent(uuid,boolean),public.get_battle_spectator_media_status(uuid),public.reserve_battle_spectator_media_viewer(uuid,uuid),public.get_battle_spectator_media_publisher_admission(uuid) from public,anon;
grant execute on function public.set_battle_spectator_media_consent(uuid,boolean),public.get_battle_spectator_media_status(uuid),public.reserve_battle_spectator_media_viewer(uuid,uuid),public.get_battle_spectator_media_publisher_admission(uuid) to authenticated;
notify pgrst,'reload schema';commit;